CONTAINER_IMAGE = "runner"
CONTAINER_MAX_MEMORY = "64m" # 64 mb
CONTAINER_NETWORKING_ENABLED = False
CONTAINER_RUNTIME = "runsc"
CONTAINER_TERMINAL = "/bin/bash"

UNTRUSTED_CODE_DIRECTORY = "home"
UNTRUSTED_CODE_FILENAME = "untrusted_code"

VALID_LANGUAGES = ["c", "cpp", "js", "py"]
