# Build the docker image to run untrusted code
# Add compilers/runtimes to install here

FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y python
RUN apt-get install -y nodejs
